version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - govuk-pay
  - dependencies
  - javascript
  ignore:
  - dependency-name: "@aws-crypto/decrypt-node"
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: "@aws-crypto/raw-rsa-keyring-node"
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: change-case
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: change-case
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: credit-card-type
    versions:
    - ">= 9.a"
    - "< 10"
  - dependency-name: cypress
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: helmet
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: standard
    versions:
    - ">= 16.a"
    - "< 17"
  - dependency-name: punycode
    versions:
    - ">= 1.5"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  ignore:
  - dependency-name: "node"
    versions:
    - ">= 18"
  open-pull-requests-limit: 10
  labels:
  - govuk-pay
  - dependencies
  - docker
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - govuk-pay
  - dependencies
  - github_actions
