module.exports = {
  ENTERING_CARD_DETAILS: 'ENTERING CARD DETAILS',
  AUTH_SUCCESS: 'AUTHORISATION SUCCESS',
  AUTH_3DS_REQUIRED: 'AUTHORISATION 3DS REQUIRED',
  AUTH_READY: 'AUTHORISATION READY',
  CAPTURE_READY: 'CAPTURE READY',
  CAPTURE_SUBMITTED: 'CAPTURE SUBMITTED',
  CREATED: 'CREATED',
  CANCELLED: 'CANCELLED'
};


