name: Post Merge

on:
  pull_request:
    paths:
      - .github/workflows/post-merge-SKIP-CI-FOR-NOW.yml
  push:
    branches:
      - master-SKIP-CI-FOR-NOW

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  publish-frontend-consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-18.04

    name: Publish and tag frontend consumer pact
    steps:
      - name: Publish frontend consumer pact file
        run: |
          pact="TODO - populate me with some JSON"

          curl -v --fail -X PUT -H "Content-Type: application/json" \
            -d@"$pact" \
            --user "${{ secrets.pact_broker_username }}:${{ secrets.pact_broker_password }}" \
            "https://pay-pact-broker.cloudapps.digital/pacts/provider/connector/consumer/frontend/version/${{ github.sha }}"
      - name: Tag the pact
        run: |
          curl -v --fail -X PUT -H "Content-Type: application/json" \
            --user "${{ secrets.pact_broker_username }}:${{ secrets.pact_broker_password }}" \
            "https://pay-pact-broker.cloudapps.digital/pacticipants/frontend/versions/${{ github.sha }}/tags/master"

  connector-provider-contract-tests:
    needs: publish-frontend-consumer-contract-tests
    uses: alphagov/pay-connector/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: frontend
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}
