name: Post Merge

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency: frontend-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  tag-release:
    needs:
      - tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
