name: Post Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: frontend-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  publish-frontend-consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-latest

    name: Publish and tag frontend consumer pact
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Parse Node version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: parse-node-version
      - name: Setup
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: "${{ steps.parse-node-version.outputs.NVMRC }}"
      - name: Cache build directories
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache pacts directory
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d
        with:
          path: pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag frontend consumer pact
        env:
          PACT_BROKER_URL: https://pay-pact-broker.cloudapps.digital
          PACT_CONSUMER_VERSION: ${{ github.sha }}
          PACT_BROKER_USERNAME: ${{ secrets.pact_broker_username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact_broker_password }}
          PACT_CONSUMER_TAG: master
        run: npm run publish-pacts

  connector-provider-contract-tests:
    needs: publish-frontend-consumer-contract-tests
    uses: alphagov/pay-connector/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: frontend
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - connector-provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
