name: Test products as provider pact

on:
  pull_request:
    paths:
      - .github/workflows/test-pact-provider.yml

permissions:
  contents: read

jobs:
  debugging:
    runs-on: ubuntu-18.04
    name: Debug
    steps:
      - name: context
        run: docker context inspect

  # products-provider-contract-tests:
  #   uses: alphagov/pay-products/.github/workflows/_run-pact-provider-tests.yml@TEST-docker-pull-in-gha
  #   with:
  #     consumer: products-ui
  #     consumer_tag: master
  #   secrets:
  #     pact_broker_username: ${{ secrets.pact_broker_username }}
  #     pact_broker_password: ${{ secrets.pact_broker_password }}
